Dataset:
  type: MNIST
  data_home: "/Users/hrvvi/Code/study/pytorch/datasets/MNIST"
  Split:
    val_ratio: 0.1
    shuffle: True
    seed: 42
  Train:
    transforms:
    - Pad:
        padding: 2
    - ToTensor:
    - Normalize:
        mean: [0.1307]
        std: [0.3081]
    batch_size: 128
    shuffle: True
    num_workers: 2
  Val:
    transforms:
    - Pad:
        padding: 2
    - ToTensor:
    - Normalize:
        mean: [0.1307]
        std: [0.3081]
    batch_size: 128
  Test:
    transforms:
    - Pad:
        padding: 2
    - ToTensor:
    - Normalize:
        mean: [0.1307]
        std: [0.3081]
    batch_size: 128


Model:
  type: LeNet5
  in_channels: 1

Optimizer:
  type: SGD
  momentum: 0.9
  lr: 0.05
  weight_decay: 0.0005

LRScheduler:
  type: CosineLR
  warmup_epoch: 5
  warmup_min_lr: 0.01
  min_lr: 0.0001

label_smooth: 0.1
Mix:
  type: CutMix
  beta: 1.0
  prob: 0.5

seed: 0
device: 'cpu'
work_dir: "./checkpoints/MNIST"
epochs: 10
eval_freq: 2
save_freq: 5

Debug:
  subset: 0.1