Dataset:
  type: MNIST
  data_home: "/Users/hrvvi/Code/study/pytorch/datasets"
  Split:
    test_ratio: 0.05
    random: True
  Train:
    transforms:
    - !Pad
      padding: 2
    - !ToTensor {}
    - !Normalize
      mean: [0.1307]
      std: [0.3081]
    batch_size: 128
    shuffle: True
    num_workers: 2
  Val:
    transforms:
    - !Pad
      padding: 2
    - !ToTensor {}
    - !Normalize
      mean: [0.1307]
      std: [0.3081]
    batch_size: 128
  Test:
    transforms:
    - !Pad
      padding: 2
    - !ToTensor {}
    - !Normalize
      mean: [0.1307]
      std: [0.3081]
    batch_size: 128


Model: LeNet5

LeNet5:
  num_classes: 10

Optimizer:
  type: SGD
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: True

LRScheduler:
  type: CosineAnnealingLR
  T_max: 100
  eta_min: 0.00001
  warmup: 1
  warmup_eta_min: 0.001

#label_smoothing: 0.1

Mix:
  type: CutMix
  beta: 1.0
  prob: 0.5

name: "MNIST-LeNet5"
seed: 0
save_path: "./checkpoints/MNIST"
epochs: 100
eval_freq: 2
save_freq: 5
prograss_bar: True

Debug:
  subset: 0.1